### ISSUE TITLE
Do we really need to separate all captcha images to five letters

### ISSUE THREAD

**Issue by LiZifan** [GCC15/bilibili-captcha#2]
![bc0bcf30-94ef-488d-a481-5c6ffed38b29](https://cloud.githubusercontent.com/assets/8919012/9023804/233c4d96-387a-11e5-8f57-5a9d7b41888c.jpg)
It is really hard to separate this image into four different letters. 
Even if we want to try separating all test images into five different letters, I think we'd better discarding those harder to separate into different letters among the training images

**Comment by zlhaa23** [comment]
Nope
