### ISSUE TITLE
partitioned failed

### ISSUE THREAD

**Issue by ktwc37** [GCC15/bilibili-captcha#7]
What that means?
Does the tool only handle image from bilibili or other captchar?

**Comment by LiZifan** [comment]
The program is designed for recognizing captchas from bilibili but might be useful for handling captchas from other sources as well. But even for captchas from bilibili, the program is not not able to recognize all of them. See readme for details.

**Comment by ktwc37** [comment]
Thank you! By the way, could this tool process 6 chars captcha? I got 'partitioned failed' when processing 6 chars.

**Comment by LiZifan** [comment]
Unfortunately the program is only able to recognize captchas comprised of five characters.
